// User-provided historical reference, not independently verified government text.
// Recommendations and industrial implications from the attachment are deliberately excluded.
export const POLICY_HISTORY = [
  {
    "id": "policy-history-1",
    "axis": "축1. 수요 지원·세제",
    "announced": "2020-04-23",
    "effective": "2020-04-23",
    "title_ko": "《关于完善新能源汽车推广应用财政补贴政策的通知》 신에너지차 보급 재정보조 정책 개선 통지",
    "document_number": "財建〔2020〕86号",
    "authority": "財政部·工信部·科技部·발改委",
    "fact_ko": "2020~2022 보조금 매년 10%·20%·30% 退坡, 실시기한 2022년말까지 연장",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-2",
    "axis": "축1. 수요 지원·세제",
    "announced": "2021-12-31",
    "effective": "2022-01-01",
    "title_ko": "《关于2022年新能源汽车推广应用财政补贴政策的通知》 2022년 보조금 통지",
    "document_number": "(財建계열, 4부문 공고형식)",
    "authority": "財政部·工信部·科技部·발改委",
    "fact_ko": "2022년 30% 退坡, 기술지표 문턱 유지, 2022.12.31 보조금 종료, 이후 상패차량 무보조",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-3",
    "axis": "축1. 수요 지원·세제",
    "announced": "2023-06-19",
    "effective": "2024-01-01",
    "title_ko": "《关于延续和优化新能源汽车车辆购置税减免政策的公告》 구매세 감면 연속·최적화 공고",
    "document_number": "財政部·税务总局·工信部公告2023年第10号",
    "authority": "財政部·税务总局·工信部",
    "fact_ko": "2024~2025 면제(승용차≤3만위안), 2026~2027 반감(≤1.5만위안); 2014년 이래 2017·2020·2022 3차 연장 이후 최초의 退坡",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-4",
    "axis": "축1. 수요 지원·세제",
    "announced": "2023-12-11",
    "effective": "2024-01-01",
    "title_ko": "《关于调整减免车辆购置税新能源汽车产品技术要求的公告》 구매세 감면 기술요구 조정 공고",
    "document_number": "工信部·財政部·税务总局公告2023年第32号",
    "authority": "工信部·財政部·税务总局",
    "fact_ko": "換電모드 GB/T 40032 등 기술요건, 목录 관리, 2024.6.1부터 부적합 차종 목록 철회",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-5",
    "axis": "축1. 수요 지원·세제",
    "announced": "2025-10",
    "effective": "2026-01-01",
    "title_ko": "《关于2026—2027年减免车辆购置税新能源汽车产品技术要求的公告》 2026~2027 구매세 기술요구 공고",
    "document_number": "工信部·財政部·税务总局公告2025年第24号",
    "authority": "工信部·財政部·税务总局",
    "fact_ko": "순수전기 전력소모 GB 36980.1-2025 한도, PHEV(증정식 포함) 등가전주행 ≥100km, PHEV 전력소모 정비질량별 <140%/145%, 기타 요건은 32호 유지",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-6",
    "axis": "축1. 수요 지원·세제",
    "announced": "2025-07-03경",
    "effective": "2027-01-01",
    "title_ko": "《关于调整节能汽车、新能源汽车车船税优惠政策的公告》 절능·신에너지차 車船稅 우대정책 조정 공고",
    "document_number": "(財政部·税务总局·工信部 공고; 번호 미확인)",
    "authority": "財政部·税务总局·工信部",
    "fact_ko": "2027.1.1부터 절능차 반감·상용 순수전기/PHEV/연료전지 면제 폐지, 財税〔2018〕74号 폐지. 순수전기·연료전지 승용차는 원래 車船稅 비과세",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-7",
    "axis": "축1. 수요 지원·세제",
    "announced": "2026-07-16",
    "effective": "2026-09-01",
    "title_ko": "《关于调整部分电池消费税政策的公告》 일부 전지 소비세 조정 공고",
    "document_number": "財政部·海关总署·税务总局公告2026年第20号",
    "authority": "財政部·海关总署·税务总局",
    "fact_ko": "원문: \"自2026年9月1日起，对无汞原电池、金属氢化物镍蓄电池、锂原电池、锂离子蓄电池、全钒液流电池按照2%税率征收消费税；自2027年9月1日起…按照4%税率\"; \"自2026年9月1日起至2028年12月31日，对钠离子电池、固态电池、燃料电池…免征消费税\"; 光伏전지 2027.4.1 2%/2028.4.1 4%; 국가표준 미달 제품 감면 불가",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-8",
    "axis": "축1. 수요 지원·세제",
    "announced": "(2023-06-29)",
    "effective": "2023-08-01",
    "title_ko": "《关于修改〈乘用车企业平均燃料消耗量与新能源汽车积分并行管理办法〉的决定》 双积分(쌍적분) 2차 개정 결정",
    "document_number": "工信部 등 5부문 令 第64号",
    "authority": "工信部·財政部·商務部·海关总署·市场监管总局",
    "fact_ko": "신에너지 표준차 분치 평균 약 40% 하향(工信部 2023.7.6 해설), 積分池(적분풀) 관리제도 신설; 후속 통지(工信部 2023.12.28)로 2024·2025년도 NEV 적분비율 각 28%·38% 확정",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-9",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2018-12-18",
    "effective": "2019-01-10",
    "title_ko": "《汽车产业投资管理规定》 자동차산업 투자관리규정",
    "document_number": "발改委 2018年第22号令",
    "authority": "국가발改委",
    "fact_ko": "내연차 신설 엄격제한, 신규 동력전지 투자시 셀 비에너지≥300Wh/kg·시스템≥220Wh/kg(意见稿), 확산기업 가동률 요건(최종본은 車用동력전지 확산기업 직전 2년 가동률≥80%)",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-10",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2019-06-24",
    "effective": "2019-06-21",
    "title_ko": "废止《汽车动力蓄电池行业规范条件》 동력전지 백명단 폐지",
    "document_number": "工信部公告2019年第22号",
    "authority": "工信部",
    "fact_ko": "2015년 제22호 및 1~4차 목록(57개사) 폐지, \"放管服\" 개혁",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-11",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2021",
    "effective": "2021",
    "title_ko": "《锂离子电池行业规范条件(2021年本)》 리튬이온전지 규범조건 2021년본",
    "document_number": "工信部公告2021年第37号",
    "authority": "工信部",
    "fact_ko": "산업규범 관리, 이후 2024년본으로 대체",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-12",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2024-06-19",
    "effective": "2024-06-20",
    "title_ko": "《锂离子电池行业规范条件(2024年本)》·《규범공고 관리办法(2024년본)》 규범조건 2024년본",
    "document_number": "工信部公告2024年第14号",
    "authority": "工信部",
    "fact_ko": "단순 산능확장 프로젝트 억제, 기술혁신·품질·원가절감 유도; 전지·정극재·음극재·격막·전해액 성능요건 상향; 2021년본(37호) 폐지",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-13",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2022-11-18경",
    "effective": "2022-11",
    "title_ko": "《关于做好锂离子电池产业链供应链协同稳定发展工作的通知》 리튬전지 산업사슬 협동안정 발전 통지",
    "document_number": "工信厅联电子函〔2022〕298号",
    "authority": "工信部办公厅·市场监管总局办公厅",
    "fact_ko": "리튬 가격급등 대응, 상하류 협동·투기 억제",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-14",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2025-11-28",
    "effective": "—",
    "title_ko": "动力和储能电池行业制造业企业座谈会 동력·ESS전지 제조업 좌담회",
    "document_number": "(좌담회, 문건 없음)",
    "authority": "工信部",
    "fact_ko": "竞争秩序 규범·고품질 발전 논의 (부장 李乐成 발언)",
    "attachment_verification": "[2차자료]"
  },
  {
    "id": "policy-history-15",
    "axis": "축2. 산업진입·생산규범·산능통제",
    "announced": "2026-01-07",
    "effective": "—",
    "title_ko": "动力和储能电池行业座谈会 동력·ESS전지 좌담회",
    "document_number": "(좌담회, 문건 없음)",
    "authority": "工信部·발改委·市场监管总局·국가能源局",
    "fact_ko": "16개사 참석(동력·ESS 13사: 宁德时代·比亚迪·中创新航·国轩高科·亿纬锂能·欣旺达·蜂巢能源·瑞浦兰钧·鹏辉能源·海辰储能·正力新能·浙江吉曜通行能源科技·楚能新能源 + 시스템집성 3사: 中车株洲所·海博思创·天合储能). \"控产能·稳价格·保护专利\", 산능감측·분급조기경보",
    "attachment_verification": "[2차자료]"
  },
  {
    "id": "policy-history-16",
    "axis": "축3. 안전·기술 표준",
    "announced": "2020-05",
    "effective": "2021-01-01",
    "title_ko": "《电动汽车用动力蓄电池安全要求》 동력전지 안전요구",
    "document_number": "GB 38031-2020",
    "authority": "市场监管总局·标委会",
    "fact_ko": "열폭주 후 5분 경보 등",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-17",
    "axis": "축3. 안전·기술 표준",
    "announced": "2020",
    "effective": "2021-01-01",
    "title_ko": "《电动汽车安全要求》·《电动客车安全要求》",
    "document_number": "GB 18384-2020 / GB 38032-2020",
    "authority": "市场监管总局·标委会",
    "fact_ko": "전기차·전기버스 안전 강제표준(3종 동시 시행)",
    "attachment_verification": "[2차자료]"
  },
  {
    "id": "policy-history-18",
    "axis": "축3. 안전·기술 표준",
    "announced": "2025-03-28",
    "effective": "2026-07-01(신규 형식승인)/2027-07-01(기승인 차종)",
    "title_ko": "《电动汽车用动力蓄电池安全要求》 동력전지 안전요구(개정)",
    "document_number": "GB 38031-2025",
    "authority": "市场监管总局·标委会",
    "fact_ko": "\"불연·불폭발\" 강제(2020년 5분 경보 → 절대안전), 바닥충격·급속충전 300회 후 외부단락 시험 신설, UN R100/GTR 20 등 국제기준 반영",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-19",
    "axis": "축3. 안전·기술 표준",
    "announced": "(2025)",
    "effective": "2026-07-01/2027-07-01",
    "title_ko": "GB 18384-2025 (전기차 안전요구 개정)",
    "document_number": "GB 18384-2025",
    "authority": "市场监管总局·标委会",
    "fact_ko": "GB 38031-2025와 동일 시행 스케줄로 형식승인 검사항목 편입",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-20",
    "axis": "축3. 안전·기술 표준",
    "announced": "2024-07-02",
    "effective": "2024-10-15 수리/2025-11-01 강제",
    "title_ko": "电动自行车用锂离子蓄电池·充电器 CCC 강제인증 공고",
    "document_number": "市场监管总局公告2024年第26号",
    "authority": "市场监管总局",
    "fact_ko": "2025.11.1부터 CCC 미인증 출고·판매·수입 금지, 셀(전심)·팩 모두 대상, 950℃ 30분 내열 각인·고유번호, 폐리튬전지 梯次이용 금지",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-21",
    "axis": "축3. 안전·기술 표준",
    "announced": "2023-03",
    "effective": "2024-08-01 강제",
    "title_ko": "电子电器产品用锂离子电池·电池组·移动电源 CCC 관리 공고",
    "document_number": "(市场监管总局 2023년 공고; 번호 미확인)",
    "authority": "市场监管总局",
    "fact_ko": "전자제품용 리튬전지·이동전원(充电宝)·전원어댑터/충전기 CCC",
    "attachment_verification": "[2차자료]"
  },
  {
    "id": "policy-history-22",
    "axis": "축4. 리사이클링",
    "announced": "2018",
    "effective": "2018-08-01",
    "title_ko": "《新能源汽车动力蓄电池回收利用管理暂行办法》 회수이용 관리잠행법",
    "document_number": "工信部联节〔2018〕43号",
    "authority": "工信部 등 7부문",
    "fact_ko": "생산자책임 확장, 회수체계",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-23",
    "axis": "축4. 리사이클링",
    "announced": "2018",
    "effective": "2018",
    "title_ko": "《回收利用溯源管理暂行规定》 추적관리 잠행규정",
    "document_number": "工信部公告2018年第35号",
    "authority": "工信部",
    "fact_ko": "全생명주기 溯源 정보플랫폼",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-24",
    "axis": "축4. 리사이클링",
    "announced": "2019",
    "effective": "2019",
    "title_ko": "《动力蓄电池回收服务网点建设和运营指南》 회수서비스망 건설·운영지침",
    "document_number": "工信部公告2019年第46号",
    "authority": "工信部",
    "fact_ko": "회수 서비스망 규범",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-25",
    "axis": "축4. 리사이클링",
    "announced": "2021",
    "effective": "2021",
    "title_ko": "《新能源汽车动力蓄电池梯次利用管理办法》 계단이용 관리방법",
    "document_number": "工信部联节〔2021〕114号",
    "authority": "工信部 등",
    "fact_ko": "梯次이용 관리",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-26",
    "axis": "축4. 리사이클링",
    "announced": "2025-12-31",
    "effective": "2026-04-01",
    "title_ko": "《新能源汽车废旧动力电池回收和综合利用管理暂行办法》 폐동력전지 회수·종합이용 관리잠행법",
    "document_number": "工信部 등 6부문 令 第73号",
    "authority": "工信部·발改委·生态环境部·交通运输部·商務部·市场监管总局",
    "fact_ko": "첫 강제성 부문규장, 전주기 溯源·차전일체 폐차·디지털신분, 18(43호)·35·46·114호 폐지, 위반 최대 50만위안",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-27",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2023-10-20",
    "effective": "2023-12-01",
    "title_ko": "《关于优化调整石墨物项临时出口管制措施的公告》 흑연 수출통제 공고",
    "document_number": "商務部·海关总署公告2023年第39号",
    "authority": "商務部·海关总署",
    "fact_ko": "고순도(>99.9%)·고강도(>30MPa)·고밀도(>1.73g/cc) 인조흑연 및 천연 인편흑연·구상흑연·팽창흑연 허가제(2006년 50호 대체)",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-28",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2024-11-15",
    "effective": "2024-12-01",
    "title_ko": "《关于调整出口退税政策的公告》 수출환급 정책 조정",
    "document_number": "(財政部·税务总局 2024년 공고)",
    "authority": "財政部·税务总局",
    "fact_ko": "성품유·光伏·전지·비금속광물제품 환급률 13%→9%",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-29",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2025-07-15",
    "effective": "2025-07-15",
    "title_ko": "《关于调整发布〈中国禁止出口限制出口技术目录〉的公告》 기술수출제한목록 조정 공고",
    "document_number": "商務部·科技部公告2025年第28号",
    "authority": "商務部·科技部",
    "fact_ko": "限制出口(허가제) 신설: 电池正极材料制备技术(编号252604X) — 원문 \"该材料在220MPa下粉体压实密度≥2.58g/cc，0.1C放电克容量≥160mAh/g，首次库伦效率≥97%\"(LFP); LMFP \"220MPa下粉体压实密度≥2.38g/cc，0.1C首次库伦效率≥95%，0.1C放电克容量≥155mAh/g，0.1C平均电压≥3.85V\"; 인산철·인산철망 등 정극원료 제조공정; 有色金属冶金技术(083201X)에 리튬휘석/염호 제리·금속리튬·卤水提锂·含锂净化液 제조기술 추가",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-30",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2025-10-09",
    "effective": "2025-11-08",
    "title_ko": "《对锂电池和人造石墨负极材料相关物项实施出口管制的决定》 리튬전지·인조흑연 음극재 물항 통제 결정",
    "document_number": "商務部·海关总署公告2025年第58号",
    "authority": "商務部·海关总署",
    "fact_ko": "리튬전지·인조흑연 음극재 관련 물항 出口管制(허가). LFP 정극재 압실밀도≥2.5g/cc·克용량≥156mAh/g 등 포함(물품 자체)",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-31",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2025-11-07",
    "effective": "2025-11-07~2026-11-10",
    "title_ko": "暂停实施 55·56·57·58·61·62号 公告的决定 통제 유예 결정",
    "document_number": "商務部·海关总署公告2025年第70号",
    "authority": "商務部·海关总署",
    "fact_ko": "55(초경질재)·56(희토설비/원부료)·57(중희토)·58(리튬전지·음극재) 및 61·62호(희토) 2026.11.10까지 유예(釜山 회담 후속)",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-32",
    "axis": "축5. 수출·통상·역외통제",
    "announced": "2026-01-08",
    "effective": "2026-04-01",
    "title_ko": "《关于调整光伏等产品出口退税政策的公告》 光伏 등 수출 VAT 환급 조정 공고",
    "document_number": "財政部·税务总局公告2026年第2号",
    "authority": "財政部·税务总局",
    "fact_ko": "전지제품 VAT 환급 2026.4.1~12.31 9%→6%, 2027.1.1 폐지(22개 전지품목); 光伏은 2026.4.1 전면폐지(249개 품목)",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-33",
    "axis": "축6. ESS 및 기타",
    "announced": "2020-10-20",
    "effective": "2020-11-02 공개",
    "title_ko": "《新能源汽车产业发展规划(2021—2035年)》 신에너지차 산업발전규획",
    "document_number": "국办发〔2020〕39号",
    "authority": "국무원판공청",
    "fact_ko": "2025년 신차판매 20%, 2035년 순수전기 주류·공공영역 전면 전동화, 동력전지 고효율 순환이용 체계",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-34",
    "axis": "축6. ESS 및 기타",
    "announced": "2021-07",
    "effective": "2021-07",
    "title_ko": "《关于加快推动新型储能发展的指导意见》 신형ESS 발전 가속 지도의견",
    "document_number": "발改能源规〔2021〕1051号",
    "authority": "발改委·국가能源局",
    "fact_ko": "원문 \"到2025年…新型储能装机规模达3000万千瓦以上\", 상업화 초기→규모화 전환",
    "attachment_verification": "[원문확인]"
  },
  {
    "id": "policy-history-35",
    "axis": "축6. ESS 및 기타",
    "announced": "2025-09-12",
    "effective": "2025-09-12",
    "title_ko": "《新型储能规模化建设专项行动方案(2025—2027年)》 신형ESS 규모화 건설 특별행동방안",
    "document_number": "발改能源〔2025〕1144号",
    "authority": "발改委·국가能源局",
    "fact_ko": "원문 \"全国新型储能装机规模达到1.8亿千瓦以上，带动项目直接投资约2500亿元，新型储能技术路线仍以锂离子电池储能为主\"(2024년말 7376만kW → 3년내 신규 1억kW 초과)",
    "attachment_verification": "[원문확인]"
  }
];
